### PR TITLE
chapter rewrites

### PR DESCRIPTION
**Pull request by emfree19**

### CODE REVIEW

**Comment by davidkane9** [comment]
Don’t add the book_temp file

**Comment by emfree19** [comment]
How do I not add book_temp.rmd? Is there a way to do this in GitHub?

**Comment by davidkane9** [comment]
1) You could delete it and then commit that deletion.

2) You could "undo" the commit which added it.

**Comment by emfree19** [comment]
I deleted the file in my repo and did pr_push(), but GitHub won’t let me make a new pull request. What should I do?
Thanks,
Emma

**Comment by emfree19** [comment]
Does this mean I no longer need to meet with Miro?

**Comment by davidkane9** [comment]
Up to you.

**Pull request merged**
