### PR TITLE
chapter 8 edits

### PR DESCRIPTION
**Pull request by Diego-arias**
added preceptor table, changed legend label, and made a few grammar orrections

### CODE REVIEW

**Comment by davidkane9** [comment]
Looks like you added a typo to chapter 7. Can you delete that change from the PR?

**Comment by Diego-arias** [comment]
Yea I did that just to push again because I was getting confused. Any
chance you can get rid of it I won’t be home for a few hours.

If not, I can fix it when I get back

**Comment by davidkane9** [comment]
No rush! Fix it later.

**Comment by Diego-arias** [comment]
fixed previous mistake

**Comment by Diego-arias** [comment]
made section less awkward

**Pull request merged**
