### PR TITLE
Productivity

### PR DESCRIPTION
**Pull request by itsyaoyu**
So far, I believe the issue is that I need to first delete my local productivity branch, go back to my master branch, pull changes from your master branch, and then create another productivity branch in order to send another pull request.

### CODE REVIEW

**Comment by davidkane9** [comment]
Fix the conflicts. See my write up in set-up.Rmd for thoughts.

**Comment by itsyaoyu** [comment]
I can't seem to access the conflicts... I can't seem to pull at all...

**Comment by davidkane9** [comment]
I will resolve the conflict

**Comment by davidkane9** [comment]
I just closed this. What happens now? Maybe you just pr_pull_upstream?

**Pull request closed without merging**
