### PR TITLE
Testing Build Workflow

### PR DESCRIPTION
**Pull request by itsyaoyu**

### CODE REVIEW

**Comment by itsyaoyu** [comment]
Need to do more research on what's causing gert to fail.

**Comment by itsyaoyu** [comment]
Failed at 95% from predict.randomForest... Why is Chapter 12 breaking?

**Comment by davidkane9** [comment]
Weird. Because it just knitted for me, and there were no changes.

Looks like same error that chapter 11 had. Creating new data to use for
prediction, but not ensuring that the factors had the same levels as in the
fitting data.

**Comment by itsyaoyu** [comment]
I just tried to knit the chapter individually and also received the same error on line 806.

**Comment by davidkane9** [comment]
Go ahead and comment out the offending code and make it a part of your push.

Make sure to pr_pull_upstream().

**Comment by itsyaoyu** [comment]
Done - waiting for build.

**Pull request merged**
